---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ redis_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install

- name: Set system overcommit policy
  sysctl:
    name: vm.overcommit_memory
    value: 1
    reload: true
    state: present
  when:
    - openio_redis_type == "redis"
    - ansible_virtualization_type != 'docker'
  tags: install

- name: Disable Transparent Huge Pages until reboot
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled && \
    echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  ignore_errors: true
  when:
    - openio_redis_type == "redis"
    - ansible_virtualization_type != 'docker'
  tags: install

- name: Disable Transparent Huge Pages for next reboot
  block:
    - copy:
        src: disable-thp.service
        dest: /etc/systemd/system/
        mode: 644
      tags: install

    - systemd:
        name: disable-thp
        enabled: true
        daemon_reload: true
      tags: install
  when:
    - openio_redis_type == "redis"
    - ansible_virtualization_type != 'docker'
...
